syntax = "proto3";

package payaja;

option go_package = "./pb";

// --- SERVICE BARU ---
service WalletService {
    // 
    rpc GetBalance (GetBalanceRequest) returns (GetBalanceResponse);
    
    // --- FITUR BARU ---
    rpc TopUp (TopUpRequest) returns (TopUpResponse);
}

message GetBalanceRequest {
    string user_id = 1;
}

message GetBalanceResponse {
    string user_id = 1;
    int64  balance = 2;
    string currency = 3;
}

// --- MESSAGE BARU ---
message TopUpRequest {
    string user_id = 1;
    int64  amount  = 2; 
}

message TopUpResponse {
    string user_id = 1;
    int64  balance = 2; 
    string status  = 3; 
}